### PR TITLE
Vc_update

### PR DESCRIPTION
**Pull request by HiDefStatic**
@gmmowry Corrected punctuation and typo (timeline to time line) on line 7. Resubmitting for teacher tag.

### CODE REVIEW

**Comment by HiDefStatic** [comment]
incorrect submission, closing

**Comment by HiDefStatic** [comment]
@gmmowry  Reopening; cannot submit in my own organization. Tagged teacher to complete assignment.

**Comment by gmmowry** [comment]
@HiDefStatic When you open a new PR with this branch, make sure you set the `base` branch to your own phase-0-tracks repository that you forked from here, not DBC's. Feel free to close this one and reopen a new one in your own repo. Thanks!

**Comment by HiDefStatic** [comment]
Resubmitted into own organization, closing request.

**Pull request closed without merging**
