### PR TITLE
Answer the questions in the version-control document

### PR DESCRIPTION
**Pull request by MattyCodes**

### CODE REVIEW

**Comment by MattyCodes** [comment]
@gmmowry

**Comment by gmmowry** [comment]
Please make sure the base branch is set to your own personal phase-0-tracks forked repository, not the DevBootcamp:master branch. Please tag me in a pull request in your own repository when you've done that. Thanks!

**Comment by MattyCodes** [comment]
@gmmowry

**Comment by gmmowry** [comment]
@MattyCodes You'll need to create a new pull request and make sure that the base is set to your own repository, not the DBC master: https://help.github.com/articles/using-pull-requests/#changing-the-branch-range-and-destination-repository

**Pull request closed without merging**
