### PR TITLE
Updated Answers

### PR DESCRIPTION
**Pull request by projectmaking123**
@Bontgoy 

Did this work?

### CODE REVIEW

**Comment by Bontgoy** [comment]
@projectmaking123 this is still the wrong repository. When making the pull request you will see the option to select the base fork.  It is s dropdown.  Select the base fork repository that matches the one you forked from Phase 0 Tracks.

Reach out if you have any questions.

**Comment by projectmaking123** [comment]
https://github.com/projectmaking123/phase-0-tracks/pull/2

I think I finally got it.

**Comment by Bontgoy** [comment]
@projectmaking123 This is still the wrong repository.  Below is a screenshot of the dropdown where you need to update the repository that you are trying to merge too.

**Comment by Bontgoy** [comment]
screen shot 2016-12-15 at 9 31 51 am

**Comment by Bontgoy** [comment]
If i was making a pull request i would be choosing the `Bontgoy/phase-0-tracks` on the dropdown.

Please close this PR and give it another shot.

**Comment by projectmaking123** [comment]
https://github.com/projectmaking123/phase-0-tracks/pull/5

Is this it?

**Comment by Bontgoy** [comment]
@projectmaking123 This continues to be the wrong repository.

Please reach out and check in with me on Slack as soon as possible.

**Comment by Bontgoy** [comment]
@projectmaking123 You are still submitting work to the wrong repository.  This means that the submissions are invalid.  Reaching out to me via email or Slack is imperative at this time if you would like to receive credit for your submissions.

**Comment by projectmaking123** [comment]
Okay, what exactly do I need, can you send me a screenshot of what the submission should look like?

**Comment by Bontgoy** [comment]
There is a screenshot on above and directions on how to properly submit right below the screenshot.

**Comment by Bontgoy** [comment]
This thread is seeming to not solve the problem and you should be using other social resources to trouble shoot with me.  I recommend Slack.

**Pull request closed without merging**
