### PR TITLE
Release 2: Tag Your Teacher

### PR DESCRIPTION
**Pull request by mk7run**
Update file 

@Bontgoy

### CODE REVIEW

**Comment by Bontgoy** [comment]
@mk7run  This is the wrong repository to make this pull request to.  Please close this PR and redo the pull request process.  This time in the `base/fork` drop down select your repository.  It is the one that you forked rom DBC-Tracks.  Then we can work on merging this successfully.

Reach out on Slack if you have any questions :)

**Comment by mk7run** [comment]
Hi Tyler,

I tried it again.
Please let me know if i did it incorrectly! :(

Melissa

**Comment by Bontgoy** [comment]
@mk7run Sorry but this is the wrong repo. Give it another shot or touch base with me in Slack if you need anything.

**Comment by Bontgoy** [comment]
@mk7run You're going to need to close this pull request otherwise each time you push this branch (try not to work on master) it will update this pr.

Reach out if you have any questions

**Pull request closed without merging**
