### PR TITLE
Tagging Teacher

### PR DESCRIPTION
**Pull request by Tonecapone21**
Tyler: Bontgoy

@Bontgoy

### CODE REVIEW

**Comment by Bontgoy** [comment]
@Tonecapone21 This is the wrong repository.  Please create a pull request on your forked version of Phase-0-Tracks and tag me there.

**Comment by Bontgoy** [comment]
@Tonecapone21 you are still pushing to the wrong repo.  Please reach out if you continue to have this issue.

**Comment by Tonecapone21** [comment]
My apologies. I'm not sure why it keeps doing this because it indicates it's my copied version of the repo.

**Comment by Bontgoy** [comment]
When you make a pull request make sure you base head is your forked repo and not the DBC master.  it is in the first dropdown during the PR

**Comment by Tonecapone21** [comment]
Very clear. Thanks you, Tyler. My apologies for any of the confusion I may have caused.

**Comment by Bontgoy** [comment]
no confusion on my end.  I knew exactly what was going wrong ;)

Im glad your back on track.  reach out if you have any other things come up

**Comment by Bontgoy** [comment]
@Tonecapone21 this is the wrong repo

Please stop making pull requests to this repository.  Reach out if there is any confusion in how to do this.

**Comment by Tonecapone21** [comment]
Hi Tyler, there definitely seems to be some confusion. On github I keep sending pull requests to Tonecapone21/phase-0-tracks, however it makes a pull request to devbootcamp/phase-0-tracks. I'm not quite sure why this happening, especially when I'm setting the pull request up in github.

**Comment by Bontgoy** [comment]
@Tonecapone21 Please choose your fork as the base fork.  Once you have completed the PR onto your repo please close this pull request on ours

Is you master up to date with all of these changes?  In other words does YOUR repository have these changes merged remotely?

**Comment by Bontgoy** [comment]
@Tonecapone21 I am closing this pull request and will close all further pull requests to this repo

**Comment by Tonecapone21** [comment]
Are you free to do a video chat and check out the workflow I have for this? I'm with my pair right now and we both walked through the pull request and I'm almost positive I did it correctly, however there still seems to be issues.

**Pull request closed without merging**
